#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'USAGE'
Install the data-product GitOps prototype into a local Argo Workflows cluster.

Usage:
  bash ./installation/install-local-argo.sh [options]

Options:
  --region <aws-region>    S3 region (default: us-east-1)
  --profile <aws-profile> AWS CLI profile to export
  --yes                   Do not ask before changing the cluster
  --skip-aws-secret       Keep the existing data-product-s3-reader Secret
  -h, --help              Show this help

The installer uses the active kubectl context and the caller's current AWS CLI
session. Temporary AWS sessions expire; rerun this command after refreshing one.
No credential values are written into this Git repository or printed.
USAGE
}

REGION=us-east-1
AWS_PROFILE=''
ASSUME_YES=false
SKIP_AWS_SECRET=false
NAMESPACE=argo

while [[ $# -gt 0 ]]; do
    case $1 in
        --region) REGION=${2:-}; shift 2 ;;
        --profile) AWS_PROFILE=${2:-}; shift 2 ;;
        --yes) ASSUME_YES=true; shift ;;
        --skip-aws-secret) SKIP_AWS_SECRET=true; shift ;;
        -h|--help) usage; exit 0 ;;
        *) echo "ERROR: unknown argument '$1'." >&2; usage >&2; exit 2 ;;
    esac
done

command -v kubectl >/dev/null 2>&1 || { echo 'ERROR: kubectl is required.' >&2; exit 2; }
command -v aws >/dev/null 2>&1 || { echo 'ERROR: AWS CLI v2 is required.' >&2; exit 2; }

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
CONTEXT=$(kubectl config current-context)
kubectl get namespace "$NAMESPACE" >/dev/null
kubectl get crd workflowtemplates.argoproj.io >/dev/null
kubectl get crd cronworkflows.argoproj.io >/dev/null

echo "Kubernetes context: $CONTEXT"
echo "Argo namespace:    $NAMESPACE"
echo "AWS region:        $REGION"
if [[ $ASSUME_YES != true ]]; then
    read -r -p 'Install/update the data-product prototype in this cluster? [y/N] ' answer
    [[ $answer == y || $answer == Y ]] || { echo 'Cancelled.'; exit 0; }
fi

if [[ $SKIP_AWS_SECRET != true ]]; then
    AWS_ARGS=()
    [[ -z $AWS_PROFILE ]] || AWS_ARGS+=(--profile "$AWS_PROFILE")
    aws "${AWS_ARGS[@]}" sts get-caller-identity >/dev/null

    CREDENTIAL_FILE=$(mktemp)
    chmod 600 "$CREDENTIAL_FILE"
    trap 'rm -f "$CREDENTIAL_FILE"' EXIT
    aws "${AWS_ARGS[@]}" configure export-credentials --format env-no-export > "$CREDENTIAL_FILE"
    set -a
    # This file is generated by AWS CLI and contains only known AWS_* assignments.
    # shellcheck disable=SC1090
    source "$CREDENTIAL_FILE"
    set +a
    rm -f "$CREDENTIAL_FILE"
    trap - EXIT

    [[ -n ${AWS_ACCESS_KEY_ID:-} && -n ${AWS_SECRET_ACCESS_KEY:-} ]] || {
        echo 'ERROR: AWS CLI did not export usable credentials.' >&2
        exit 1
    }
    SECRET_ARGS=(
        --from-literal="AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
        --from-literal="AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
        --from-literal="AWS_REGION=$REGION"
        --from-literal="AWS_DEFAULT_REGION=$REGION"
    )
    [[ -z ${AWS_SESSION_TOKEN:-} ]] || SECRET_ARGS+=(--from-literal="AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN")
    kubectl -n "$NAMESPACE" create secret generic data-product-s3-reader \
        "${SECRET_ARGS[@]}" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
    unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
    echo 'Reconciled Secret data-product-s3-reader.'
fi

kubectl apply -f "$REPO_ROOT/argo/templates/"
kubectl apply -f "$REPO_ROOT/argo/workflow-template.yml"
kubectl apply -f "$REPO_ROOT/argo/reconciler.yml"

echo
echo 'Installation complete.'
kubectl -n "$NAMESPACE" get workflowtemplates.argoproj.io
kubectl -n "$NAMESPACE" get cronworkflow reconcile-data-product-manifests
echo
echo "Watch reconciliation with: kubectl -n $NAMESPACE get workflows,pods -w"
