apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-product-reconciler
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: data-product-reconciler
  namespace: argo
rules:
  - apiGroups: [argoproj.io]
    resources: [workflows]
    verbs: [get, list, create]
  - apiGroups: [argoproj.io]
    resources: [workflowtaskresults]
    verbs: [create, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-product-reconciler
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: data-product-reconciler
    namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: data-product-reconciler
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-product-deployer
  namespace: argo
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: reconcile-data-product-manifests
  namespace: argo
spec:
  schedules:
    - "* * * * *"
  concurrencyPolicy: Forbid
  workflowSpec:
    serviceAccountName: data-product-reconciler
    entrypoint: reconcile
    templates:
      - name: reconcile
        container:
          image: ghcr.io/t-sterling/data-product-reconciler:0.1.0
          env:
            - {name: ENVIRONMENT, value: dev}
            - {name: ARGO_NAMESPACE, value: argo}
            - {name: DEPLOYMENT_REPOSITORY_URL, value: "https://github.com/t-sterling/data-product-deployment.git"}
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: deployment-repository-credentials
                  key: token
                  optional: true
